library(readr)
data=read.csv("C:/Users/dell/Desktop/semester 3/applied stats/sample.csv")
View(data)
View(list_data)
summary(data)
mean(data$MURDER)
pie(data$YEAR)
barplot(data$ATTEMPT.TO.MURDER)
histogram(data$DISTRICT)
boxplot(data$STATE.UT)
